### ISSUE TITLE
Discrepancy between example and code

### ISSUE THREAD

**Issue by movence** [epoberezkin/ajv-errors#10]
"**Messages for keywords**" says that I can pass a single string value for a keyword
`errorMessage: {
    required: 'field is required.'
  }`
But doing so throws an error saying that "data.properties['errorMessage'].required" expects an array rather than a string.

Also, keyword error message does not seem to work because the error message is just a plain JSON validation error message.

**Expected**:
`
{ keyword: 'required',
    dataPath: '',
    schemaPath: '#/required',
    params: { missingProperty: 'someField' },
    message: 'field is required.'' } ]
`
**Actual**:
`
{ keyword: 'required',
    dataPath: '',
    schemaPath: '#/required',
    params: { missingProperty: 'someField' },
    message: 'should have required property \'someField\'' } ]
`

**Comment by epoberezkin** [comment]
There is a test that tests exactly this scenario: https://github.com/epoberezkin/ajv-errors/blob/master/spec/object.spec.js#L19

Please submit your code example to runkit that produces this result. The expected error would have "keyword" equal to "errorMessage". It may be that you are putting your error message in the wrong place.

**Comment by epoberezkin** [comment]
Looking at the error message: `data.properties['errorMessage'].required` means that you've put it inside "properties" keyword, so "errorMessage" is interpreted as a property name and "required" inside it just as a normal keyword. "errorMessage" should be a sibling to "properties", not a child.

**Comment by movence** [comment]
Ha! I totally missed it. Thanks for looking into my question.
