### ISSUE TITLE
More fine grained control?

### ISSUE THREAD

**Issue by superandrew213** [epoberezkin/ajv-errors#11]
Any plans to add more fine grained control? Like you mentioned [here](https://github.com/epoberezkin/ajv/issues/100#issuecomment-230351478).

Example:

```
{
  "type": "object",
  "properties": {
    "size": {
      "type": "number",
      "minimum": 4
    }
  },
  "errorMessage": {
    "properties": {
      "size": {
        "type": "Size must be a number",
        "minimum": "Size cannot be less than 4"
      }
    }
  }
}
```

**Comment by epoberezkin** [comment]
That's what is there in the link you posted (and that's how can use it):

```json
{
  "type": "object",
  "properties": {
    "size": {
      "type": "number",
      "minimum": 4
      "errorMessage": {
        "type": "Size must be a number",
        "minimum": "Size cannot be less than 4"
      }
    }
  }
}
```

**Comment by superandrew213** [comment]
It wasn't working before. I must have missed something. But now of course it's working. Thanks!

**Comment by superandrew213** [comment]
When a type error occurs, the other errors are triggered too. Is there a better way to show only type error message other than going through the errors list and looking for type errors?

**Comment by epoberezkin** [comment]
I don't understand. What's the schema/data and what are the messages? When you say "triggered" what exactly do you mean?

**Comment by superandrew213** [comment]
If I validate `{ size: 'abc' }` in the above example, it will return both type and minimum error.

**Comment by epoberezkin** [comment]
It doesn't for me: https://runkit.com/esp/593d4c73c899fe001280d79c

**Comment by epoberezkin** [comment]
"minimum" etc. only get validated for numbers, it should not generate any errors if the data is not a number.

**Comment by superandrew213** [comment]
My mistake, it seems that my application is converting strings to `NaN`.

**Comment by superandrew213** [comment]
Should it still trigger both type and minimum errors?

**Comment by epoberezkin** [comment]
for NaN? Yes, because typeof NaN is "number".

**Comment by superandrew213** [comment]
Yes, but why is it generating a type error?

**Comment by epoberezkin** [comment]
it doesn't for me: https://runkit.com/esp/593d4c73c899fe001280d79c

**Comment by epoberezkin** [comment]
See https://github.com/epoberezkin/ajv/issues/182

**Comment by superandrew213** [comment]
Thanks for the link to the discussion. I'm testing a lot of different types and the type and minimum error were both generated when `"type": "integer"` with `{ size: NaN }`.

```
{
  "type": "object",
  "properties": {
    "size": {
      "type": "integer",
      "minimum": 4,
      "errorMessage": {
        "type": "Size must be an integer",
        "minimum": "Size cannot be less than 4"
      }
    }
  }
}
```

**Comment by epoberezkin** [comment]
NaN is not an integer. But minimum applies to it because it is a number.

**Comment by superandrew213** [comment]
Ok got it. A bit confusing though.
