### ISSUE TITLE
if you define some property specific errors for required keyword, you should define errors for all properties.

### ISSUE THREAD

**Issue by skilFullGH** [epoberezkin/ajv-errors#14]
If i write so
```js
var Ajv = require('ajv');
var ajv = new Ajv({allErrors: true, jsonPointers: true});
require('ajv-errors')(ajv);

var data = {}

var valid = ajv.validate({
  'required': ['p1', 'p2'],
  'errorMessage': {
    'required': {
      'p1': 'some p1 error',
      'p2': 'some p2 error'
    }
  }
}, data);

if (!valid) console.log(ajv.errors);
```
all work. If so
```js
var Ajv = require('ajv');
var ajv = new Ajv({allErrors: true, jsonPointers: true});
require('ajv-errors')(ajv);

var data = {}

var valid = ajv.validate({
  'required': ['p1', 'p2'],
  'errorMessage': {
    'required': {
      'p1': 'some p1 error'
    }
  }
}, data);

if (!valid) console.log(ajv.errors);
```
script stops.
node: 8.4.0

**Comment by epoberezkin** [comment]
https://github.com/epoberezkin/ajv-errors/issues/14

So the current limitation is that if you define some property specific errors for `required` keyword, you should define errors for all properties.

Should be relatively simple to fix. PR is welcome.

**Comment by skilFullGH** [comment]
Ok, thanks for the quick response

**Comment by kenziD** [comment]
same problem ,cost me an hour to realize the problem is because of this.hope to fixed it as soon as possible.I use ajv-error to validate ajax response content,and this error block the network ,make the network pending,really wired.

**Comment by robblaura** [comment]
We just encountered this error as well, spent over an hour tracking down the problem.

**Comment by Aleksandras-Novikovas** [comment]
PR created.
