### ISSUE TITLE
Name of missing 'required' property.

### ISSUE THREAD

**Issue by Aleksandras-Novikovas** [epoberezkin/ajv-errors#21]
```
var schema = {
  type: 'object',
  required: ['foo', 'bar'],
  errorMessage: {
    required: {
      foo: 'missing foo property',
      bar: 'missing bar property'
    }
  }
```
Processed errors:
```
[
  {
    keyword: 'errorMessage',
    message: 'missing foo property',
    dataPath: '',
    // ...
  },
  {
    keyword: 'errorMessage',
    message: 'missing bar property',
    dataPath: '',
    // ...
  }
]
```
It is difficult to know which error message was generated for which property.
It is needed for automatic processing.
Now there are two possible workarounds:
1. format error message in a special way (include missing property name) and process it afterwards
2. check param.errors[0].missingProperty - here we have to make sure that param.errors[0].keyword==="required"

Suggestion:
Add name of missing property to dataPath. This is possible only when property specific message is defined.

Another suggestion:
Add option allowing to have separate messages for missing properties (even if single error message is defined for all missing properties). This would allow to have correct dataPath settings for every missing property.

**Comment by epoberezkin** [comment]
I think approach 2 is ok, why is it a workaround? "required" keyword validates an object, not a property, so dataPath is correct.

**Comment by Aleksandras-Novikovas** [comment]
Yes, "required" keyword validates object but "errorMessage.required" allows to have different messages for separate "missing" properties. As you can see from my example there is no direct way to know which message (in error object array) meant for which property within this object. In my projects I add property name to the start of error message to make error processing simpler. It would be more robust solution to receive missing property name from validator.

Simple use case would be:
user fills-in form and posts data to server;
server validates and returns errors with missing required fields;
client application highlights corresponding input fields and shows corresponding message;
Now there is no easy way for client to determine which exact fields were missing and which error message should be shown for which input field.

**Comment by YannOntiime** [comment]
I have the same need and I have developed the beginning of a function that allows to return an array of objects of type : 



```
[
    
    {
        "field": "email",
        "message": "email must be a string and is required"
    }, 
    {
        "field": the name of the field,
        "message": message error
    },
]
```




```
function ajvErrorsToArray(ajvErrors: Array<{}>) {
  let errors: Array<{}> = [];
  ajvErrors.forEach((error: any) => {
    let e: { field: string | null; message: string | null } = {
      field: null,
      message: null,
    };
    if (error.instancePath === "") {
      error.params.errors.forEach((paramsError: any) => {
        if (paramsError.keyword === "required") {
          if (error.message) {
            e.field = paramsError.params.missingProperty;
            e.message = error.message;
          } else {
            e.field = paramsError.params.missingProperty;
            e.message = paramsError.message;
          }
        }
      });
    } else {
      e.field = error.instancePath.substring(1);
      e.message = error.instancePath.substring(1) + " " + error.message;
    }
    errors.push(e);
  });

  return errors;
}
```
