### ISSUE TITLE
Keyword error for if-clause failure

### ISSUE THREAD

**Issue by Jerdak** [epoberezkin/ajv-errors#29]
Similar to #13, is there a way catch the error in the if schema so that only it gets reported.  The only way to catch the if-clause seems to be a top-level errorMessage on `if`, however this then gets report if the then schema fails as well.  Placing an `errorMessage` in the `if` schema appears to do nothing.

This could just be a matter of me not knowing how to "throw" an error other than with `else: false`.  

```
const Ajv = require("ajv");

const ajv = new Ajv({
    "allErrors": true,
    "jsonPointers": true
});
require('ajv-errors')(ajv);
    
const schema = {
    "type":"object",
    "properties": {
        "foo": {
            "type":"string",
            "if":{
                "maxLength":5
            },
            "then":{
                "enum":["bar"],
                "errorMessage":{
                    "enum":"then-clause failed"
                }
            },
            "else":false,
            "errorMessage":{
                "if":"if-clause failed."
            }
        }
    }
}

let validate = ajv.compile(schema);
console.log(validate({"foo":"baz"}));
console.log("Errors:",ajv.errorsText(validate.errors));
```
https://runkit.com/jerdak/keyword-error-for-if-clause-failure

Prints `"Errors: data/foo then-clause failed', data/foo if-clause failed."`  

Ideally I would like to customize the error for the `if` failure without having to double check the `maxLength`, once for the `if` schema and once at the property schema level.

**Comment by epoberezkin** [comment]
“If” on it’s own never fails - it simply defines which schema is used “then” or “else”. If the chosen schema is absent, the validation will succeed.

**Comment by Jerdak** [comment]
Yep, I get that.  My question was more is there a way to tailor an error specific to an `else` without a schema.  Or maybe this is more of a JSON Schema question of is there a native way to throw a false and catch it in the `else`
