### ISSUE TITLE
AJV validator and custom or user-friendly error message

### ISSUE THREAD

**Issue by leoamp** [epoberezkin/ajv-errors#38]
I have the following schema and json to validate using ajv. I am developing a REST API that takes a JSON and gets validated against the schema and it returns the error (400- with the ajv error) or (200 - when successfully validated)

//Assuming ajv, ajv-errors npm are installed properly

```
const schema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [ "countries" ],
  "definitions": {
    "europeDef": {
      "type": "object",
      "required": ["type"],
      "properties": { "type": {"const": "europe"} }
    },
    "errorMessage":"Country type should be europe only"
    "asiaDef": {
      "type": "object",
      "required": ["type"],
      "properties": { "type": {"const": "asia"} }
    },
    "errorMessage":"Country type should be asia only"
  },
  "properties": {
    "countries": {
      "type": "array",
      "items": {
        "oneOf":[
          { "$ref": "#/definitions/europeDef" },
          { "$ref": "#/definitions/asiaDef"}
        ]
      }
    }
  }
}
```
```
const data = {
  "countries":[
    {"type": "asia1"},
    {"type": "europe"}
  ]
}
```
```
const isValid = ajv.validate(schema, data); //schema, data
if(! isValid){
  console.log(ajv.errors);
}

```
and the error is:
```
[
  {
    keyword: 'errorMessage',
    dataPath: '/countries/1',
    schemaPath: '#/definitions/europeDef/errorMessage',
    params: { errors: [Array] },
    message: 'Country type should be europe only'
  },
  {
    keyword: 'errorMessage',
    dataPath: '/countries/1',
    schemaPath: '#/definitions/asiaDef/errorMessage',
    params: { errors: [Array] },
    message: 'Country type should be asia only'
  },
  {
    keyword: 'oneOf',
    dataPath: '/countries/1',
    schemaPath: '#/properties/countries/items/oneOf',
    params: { passingSchemas: null },
    message: 'should match exactly one schema in oneOf'
  }
]
```

I know why the error is appearing (reason: as I have used 'asia1' and it is not conforming the schema standard). Here, the problem is with "asia", but the ajv is giving the error mesage for 'europe' too (despite it is correct)

My question is, as I have derived this schema so I can pretty much understand the error. But for a third person it would definitely take some time to figure it out (and it may take more time, if the schema/errors are more complex).

If I returned that whole error message as a response as it is, it will be more complex error message to understand and to present to the enduser.

So, Is there any way by which I can provide more meaningful & user friendly/specific error message to understand using this ajv-errors npm? I tried but not able to make it possible using this npm.
ex: Invalid asia1 found for country type found.

P.S: Originally asked at SoF: [Link](https://stackoverflow.com/questions/59544941/ajv-validator-and-custom-or-user-friendly-error-message) and slightly updated for this issue in this git repo.

**Comment by epoberezkin** [comment]
You can use if/then/else or custom select (from ajv-keywords) to avid validating branches that are known to be invalid because of the `type` tag. There is an ticket in Ajv to change oneOf validation to use discriminator keyword to achieve the same behaviour, but it is not implemented yet.
